CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(100) NOT NULL,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password_hash VARCHAR(255) NOT NULL,
                       role_id BIGINT NOT NULL,
                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       CONSTRAINT fk_users_role
                           FOREIGN KEY (role_id)
                               REFERENCES roles (id)
                               ON DELETE RESTRICT
);

CREATE TABLE movies (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title VARCHAR(255) NOT NULL,
                        description TEXT NOT NULL,
                        release_year INT NOT NULL CHECK (release_year >= 1888),
                        duration_minutes INT NOT NULL CHECK (duration_minutes > 0),
                        country VARCHAR(100) NOT NULL,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE genres (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE movie_genres (
                              movie_id BIGINT NOT NULL,
                              genre_id BIGINT NOT NULL,
                              PRIMARY KEY (movie_id, genre_id),
                              CONSTRAINT fk_movie_genres_movie
                                  FOREIGN KEY (movie_id)
                                      REFERENCES movies (id)
                                      ON DELETE CASCADE,
                              CONSTRAINT fk_movie_genres_genre
                                  FOREIGN KEY (genre_id)
                                      REFERENCES genres (id)
                                      ON DELETE RESTRICT
);

CREATE TABLE ratings (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         value INT NOT NULL CHECK (value BETWEEN 1 AND 10),
                         user_id BIGINT NOT NULL,
                         movie_id BIGINT NOT NULL,
                         created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         CONSTRAINT uq_ratings_user_movie UNIQUE (user_id, movie_id),
                         CONSTRAINT fk_ratings_user
                             FOREIGN KEY (user_id)
                                 REFERENCES users (id)
                                 ON DELETE RESTRICT,
                         CONSTRAINT fk_ratings_movie
                             FOREIGN KEY (movie_id)
                                 REFERENCES movies (id)
                                 ON DELETE CASCADE
);

CREATE INDEX idx_movies_release_year ON movies (release_year);
CREATE INDEX idx_movie_genres_genre_id ON movie_genres (genre_id);
CREATE INDEX idx_ratings_movie_id ON ratings (movie_id);